; ACZ main include file
; Assembly Coder's Zenith - http://www.acz.org
; version: January 18, 1999

#include "inc/Asm86.h"	; flags, key equates...
#include "inc/Ram86.h"	; memory locations
#include "inc/Rom86.h"	; ROM calls

.end

;==========================================================
; 					C R E D I T S
;==========================================================
;If you find something wrong with these include files,
;feel free to e-mail me (clem@acz.org)
;Many thanks to Joshua Seagoe for his ROM calls list
;and to Pat Milheron for all the TI-86 info ;-)
;__________________________________________________________
;(C)1999 ACZ - Assembly Coder's Zenith - http://www.acz.org
