name: Compile .86p On Commit

on:
  push:
    branches: [ master ]
    paths: 'asm/**'
  pull_request:
    branches: [ master ]
    paths: 'asm/**'

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Run asm/build.bat
      run: asm/build.bat
      shell: cmd

    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path: asm/out

    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: Logs
        path: asm/log
