name: Compile .86p On Commit

on:
  push:
    branches: [ master ]
    paths: 'asm/**'
  pull_request:
    branches: [ master ]
    paths: 'asm/**'
  workflow_dispatch:

jobs:
  tasm:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run TASM
      shell: cmd
      run: |
        cd asm\scripts
        tasm.bat

    - name: Upload intermediary binary
      uses: actions/upload-artifact@v2
      with:
        name: TASM
        path: |
          asm/build/pongiii.bin
          asm/build/pongiii.lst

  build:
    runs-on: ubuntu-latest
    needs: [tasm]

    steps:
    - uses: actions/checkout@v2
      
    - name: Download TASM intermediary binary
      uses: actions/download-artifact@v2
      with:
        name: TASM

    - name: Run binpac8x and trim assembly listing
      run: asm/scripts/pack.sh && sed -n -e '/org _asm_exec_ram/,// p' pongiii.lst > asm/out/pongiii.lst

    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: Output
        path: asm/out
