name: Compile .86p On Commit

on:
  push:
    branches: [ master ]
    paths: 'asm/**'
  pull_request:
    branches: [ master ]
    paths: 'asm/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies in Runner Shell
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y wine-stable wine32

    - name: Run asm/build.sh
      run: asm/build.sh

    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path: asm/out

    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: Logs
        path: asm/log
