# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies in Runner Shell
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y wine-stable wine32

    - name: Run asm/build.sh
      run: asm/build.sh

    - name: Upload ouput
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path: asm/out/pongiii.86p
