name: Compile PS-EXE On Commit

on:
  push:
    branches: [ master ]
    paths: 'PSX/**'
  pull_request:
    branches: [ master ]
    paths: 'PSX/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      submodules: true
  
#    - name: Set ownership
#      run: sudo chown `id -un`:`id -gn` -R /home/runner/*

    - name: Prepare SDK
      run: cd PSX/SDK && ./install_headless.sh

    - name: Compile
      run: PSX/compile.sh

    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: Output
        path: PSX/out
